In [1]:
import pandas as pd

In [2]:
nov = pd.read_csv('datasets/november_final.csv')

In [3]:
nov

,Intersection,01_11_2019 06_00_01,01_11_2019 06_00_31,01_11_2019 06_01_01,01_11_2019 06_01_31,01_11_2019 06_02_01,01_11_2019 06_02_31,01_11_2019 06_03_01,01_11_2019 06_03_31,01_11_2019 06_04_01,...,30_11_2019 23_55_01,30_11_2019 23_55_31,30_11_2019 23_56_01,30_11_2019 23_56_31,30_11_2019 23_57_01,30_11_2019 23_57_31,30_11_2019 23_58_01,30_11_2019 23_58_31,30_11_2019 23_59_01,30_11_2019 23_59_31
0,"senparaparbata(23.80581,90.36912)-mirpur10circ...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,"mirpur10circle(23.80702,90.36851)-mainroad(23....",0,72,0,72,72,72,72,72,72,...,0,0,0,0,0,0,0,0,0,0
2,"mirpur2bs(23.80511,90.36343)-mainroad(23.8067,...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,"mainroad(23.8067,90.36689)-mirpur2bs(23.80511,...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,"mirpurcollegeroad(23.80339,90.36074)-mirpur2bs...",0,0,0,0,44,37,37,44,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,"mirpuroriginal10(23.8102909,90.3675265)-avenue...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
150,populardiagnosticcenter(4579879715)(23.8095357...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
151,"mirpuroriginal10(23.8102909,90.3675265)-popula...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
152,"proshikamorebusstop(23.8096296,90.3610100)-nat...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
153,"proshikamorebusstop(23.8096296,90.3610100)-bra...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
dec = pd.read_csv('datasets/december_final.csv')

In [12]:
dec.loc[1:,:].reset_index().drop(columns = ['index']).to_csv('datasets/december_final.csv',index = False)

In [14]:
jan = pd.read_csv('datasets/january-2020_final.csv')

In [19]:
jan = jan.loc[1:,:].reset_index().drop(columns = ['index'])

In [22]:
jan.rename(columns={'roads':"Intersection"},inplace=True)

In [24]:
jan.to_csv('datasets/january-2020_final.csv',index=False)